hack4impact-uiuc/memberdb-tool

- api/package.json
- api/src/app.js
- api/src/appListener.js
- api/src/middleware/errorWrap.js
- api/src/models/member.js
- api/yarn.lock
Create the DB model for a H4I member.
Closes #3
> Create member DB model

- api/src/app.js
- client/src/App.js
- client/src/components/Profile/Profile.js
- client/src/components/navbar/Navbar.js
- client/src/components/table/Table.js
- client/src/css/Login.css
- client/src/index.js
- client/src/pages/Home.js
- client/src/pages/Login.js
- client/src/pages/Member.js
- client/src/routes.js
- client/src/utils/apiHelpers.js
- client/src/utils/apiUrls.js
- client/src/utils/apiWrapper.js
Removes Authentication state and connects the Frontend Authentication to the Backend API
- Created API urls to abstract some literals into constants
- Created API Helper to abstract URL building on frontend
- Integrated Backend Google Auth by redirecting to backend API for authentication 
- Removed Sample POST and Sample GET Requests
- Removed startUserSession Request 
- Fixed CORS for proper authentication
- Added documentation for methods
- Removed login and logout functions along with their prop-type validations
https://user-images.githubusercontent.com/66758185/104538819-3976f800-55e2-11eb-8484-ac0a96bb9f1b.mp4
```
if (environment != 'production') {
// For authentication to work on CORS, we must specify a non-wildcard origin
// and allow credentials (cookies)
app.use(cors({ origin: …
```
> Frontend-Backend Auth connection

- api/src/app.js
- api/src/routes/index.js
Remove extraneous router in routes/index.js. It's an extra directory/router since we have src/api already.
> Remove extraneous router in routes/index.js

- api/src/models/member.js
Add null to enum options so default of null for those fields works
> Add null to enum options so default works

- api/src/api/members.js
- api/src/utils/user-utils.js
closes #53 
Validates specified fields in the backend given a regex. 
It supports multiple variations of phone numbers. Whether they are spaced using '.' , '-', or space
- Added regex testing for specified fields
- updated validateMemberQuery to support the regex
> String validation

- client/package.json
- client/src/components/table/Table.js
- client/src/utils/tableHelpers.js
- client/yarn.lock
Description of PR here...
Missing fields on the table were either being called wrong or compared incorrectly so I updated them to fully match how the backend sends out data.
- added UIN, netID, and other missing fields 
- added formatting for human readability birthdates
- updated comparators and added moment.js
Closes #51
> Missing Fields

- api/src/api/notes.js
Changed endpoints so that they work with rigorous testing
- Fixed get request for notes
- Tested all endpoints
> Fix and test endpoints

- api/src/api/notes.js
Add handling of version control to PUT and POST endpoints.
- Add version control for POST
- Add version control for PUT
> Add version control for put requests

- api/src/api/notes.js
Update the endpoints so that they return member data.
- Updated get request to return member object data
**Request**
(Only for backend)
GET `/api/notes` Returns a list of notes
**Response**
(Only for backend)
HTTP/1.1 200 OK
```
{
"success": true,
"result": [
{
"_id": "600b5a863079290d2c934d2a",
"metaData": {
"access": {
"viewableBy": [
{
"memberId": "60038c036cb5611a649e6b46",
"name": "Daniel Moon"
}
],
"editableBy": [
{
"memberId": "60038c036cb5611a649e6b46",
"name": "Daniel Moon"
}
]
},
"title": "Test",
"labels": [
"1V1",
"Interview"
],
"referencedMembers": [
{
"memberId": "60038c036cb5611a649e6b46",
"name": "Daniel Moon"
}
],
"versionHistory": [
{
"default": [],
"date": "2021-01-22T23:06:46.677Z",
"memberID": "123456789",
"action": "CREATED",
"_id": "600b5a863079290d2c934d2b"
}
], …
```
> Change get endpoint to return member object

- api/src/api/notes.js
Edit GET endpoint to fix a bug.
> Ad get endpoint fix

- api/src/api/notes.js
Edit get so that editableBy permissions also give viewableBy
Closes: #75
> EditableBy has viewable by default

- api/src/api/members.js
- api/src/utils/user-utils.js
- client/src/App.js
- client/src/components/EditableAttribute/DateAttribute.js
- client/src/components/EditableAttribute/TextAttribute.js
- client/src/components/navbar/Navbar.js
- client/src/css/Navbar.css
- client/src/pages/Profile.js
- client/src/utils/apiWrapper.js
- client/src/utils/consts.js
- updated profile page to support create a new member
- redirects after creating member and updates database
- added createMember wrapper endpoint
> Add Members UI

- client/src/App.js
- client/src/pages/Note.js
Note editor quality of life updates.
- Success feedback on good request (update or creation)
- Creating a new note forwards users to the new note's route
- User is added by default to both viewableBy and editableBy list
- Viewing-only mode for viewers of the file
Closes #73 , Closes #74
> Fix Default Viewer/Editor, View-Modes

- api/yarn.lock
- client/package.json
- client/src/App.js
- client/src/components/routes/PrivateRoute.js
- client/yarn.lock
If accessing a protected route without authentication, automatically redirect to login page. Closes #90
> Add private routing

- client/src/components/routes/PrivateRoute.js
Fixes the routing issue by passing the component as a child.
> Fix routing issue

- api/src/api/notes.js
- api/src/app.js
- client/src/pages/Note.js
- Sets a smaller rate limit for auth
- Fixes frontend render bug
> Add differing rate limits per route, fix rendering bug

- api/src/api/notes.js
- api/src/app.js
- client/src/pages/Note.js
- Disables update/create button while waiting for API response
- Fixes bug that was hanging the API when response error was missing
Fixes #87
> Improve create and update note behavior

- api/src/api/projects.js
- api/src/models/chapters.js
- api/src/models/members.js
- api/src/models/projects.js
- api/src/utils/members.js
- api/tools/db_population_tool.js
Added the schemas for Projects and Chapters! The Design spec is available [here](https://www.notion.so/h4i/Design-ab8db4b66f2c46e1af30fbcdf6fb888f#15c5ff76c70248b1bb2d25397a8b76e2)
> Added schemas

- api/src/api/index.js
- api/src/api/members.js
- api/src/api/projects.js
This is to Migrate these two PRs:
[Get projects/members of chapters](https://github.com/hack4impact/memberdb-tool/pull/6/files)
[Add chapter routes and model](https://github.com/hack4impact/memberdb-tool/pull/5)
And most of this PR:
[Added Api routes for deleting members and adding multiple members
](https://github.com/hack4impact/memberdb-tool/pull/2)
> PR migration: Get Members of Chapter API, Bulk Add Members API

- client/src/App.jsx
- client/src/components/navbar/Navbar.jsx
- client/src/pages/Projects.jsx
- client/src/routes.js
- client/src/utils/apiWrapper.js
- client/src/utils/tableHelpers.js
- Added a Projects button to the Navbar that navigates to /projects
- Created Projects page that will display all projects 
- created projectTableDefs in tableHelpers.js for table headers on the Projects page. I based them on the Project schema defined in api/src/models/projects.js
> Add Projects to the NavBar, create getAllProjects() function

- api/src/api/projects.js
:rocket: Ready
Finished a route that gets all projects of a chapter. I'm still getting the circular JSON error when making any find queries, not sure what's causing it.
> Added route to get all projects of a chapter

- api/src/api/projects.js
- api/yarn.lock
- client/src/components/layout/Page.jsx
- client/src/components/table/Table.jsx
The goal for this PR is to add a few Project APIs, as well as fixing some minor issues.
> Added Create and Update Project APIs, fixed some minor issues

- client/src/components/WarningModal/WarningModal.jsx
- client/src/css/WarningModal.css
:rocket: Development
Created the warning modal component for displaying warnings and error messages to the user.
> Create warning modal component (#121)

- api/src/app.js
This PR adds support for accessing session cookies on subdomains of `h4i.app`. This allows us to leverage the memberDB tool for authentication.
> Add cookie subdomain support

- api/src/api/projects.js
> Fixed projects for now

- api/src/api/chapters.js
- api/src/models/chapters.js
:construction: In development
The code should be done, I just haven't been able to test it since I've been having issues connecting to the db. Please don't merge until you've tested the api route I wrote!
> Added table layout field

- client/src/components/Label/ClickLabel.jsx
- client/src/components/Label/Label.css
- client/src/components/Label/Label.jsx
- client/src/components/Label/labelColors.js
:rocket: Ready
Finished the label component! The two versions are called `<Label>` and `<ClickLabel>`. Also added labelColors.js which contains some of the most common colors for labels. Let me know if you have any questions or suggestions!
> Added Label Component
